spring.application.name=projetolistadetarefas

spring.datasource.username=root

spring.datasource.password=mysql

spring.datasource.url=jdbc:mysql://localhost:3306/todolist?useTimezone=true&serverTimezone=UTC

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.show_sql=true


